### ISSUE TITLE
Rendering bug for polygonal layer

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_nextgis_mobile#1]
Shows a weird star-like pattern, supposed to be a grid of polygons.

*.prj file is missing, can this be a reason?

https://www.dropbox.com/s/js487lprog7c6lw/eoa.zip?dl=0

**Comment by NikitaFeodonit** [comment]
Fixed:
https://github.com/nextgis/nextgis_datastore/commit/0d6b8e21f863e0646203add1428893e462fc7899
