### ISSUE TITLE
Line layer crashes NGM

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_nextgis_mobile#16]
Example
[railway.zip](https://github.com/nextgis/android_nextgis_mobile/files/707971/railway.zip)

**Comment by simgislab** [comment]
still crashes in ngmobile3-0.5-release.apk

**Comment by BishopGIS** [comment]
This is nextgis_store bug. Fixed in https://github.com/nextgis/nextgis_datastore/commit/6f4a8ad420136c3fa3898245b888da74d292b668
